### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by akournitsky** [merri-ment/lazy-line-painter#81]
Hi,

Your library is a cool thing, but :-) ... 
WIX has just added lazy-lane-painter npm to their repository according my request. 
Now I am trying just to import it and at this point (import lazyLinePainter from 'lazy-line-painter';) I get "ReferenceError: window is not defined"

What's wrong?

Just as an idea - as far as I understand you have no access to CSS using JS in WIX, maybe that's why?

**Comment by kendreaditya** [comment]
Did you ever find a solution? From the research I have done, it seems as though "window" is referenced in the package's code and "window" is not defined [due to the structure of a WixCode](https://www.wix.com/velo/forum/community-discussion/printing-a-wix-web-page).

**Comment by merri-ment** [comment]
the code must run on a node server which doesn't have access to window. 
this has been fixed in 2.0.0
